# Generated by Django 3.0.7 on 2020-07-05 16:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reviews', '0001_initial_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('reviews_day', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'DomainName',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IpList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'IpList',
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=254)),
                ('reviews', models.TextField()),
                ('star', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('publish', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.DomainName')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.IpList')),
            ],
            options={
                'verbose_name': 'Reviews',
                'ordering': ['name', 'star'],
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('banned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('banned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.IpList')),
            ],
            options={
                'verbose_name': 'BlackList',
                'ordering': ['ip_address', 'banned_at'],
            },
        ),
    ]
